# Generated by Django 5.2.1 on 2025-07-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quibly_core', '0003_tweet_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='quibly_core.userprofile'),
        ),
    ]
